import { computed, ref } from 'vue';

export const supportedLocales = ['it', 'en', 'ru'] as const;
export type Locale = typeof supportedLocales[number];

const messages = {
  it: {
    brand: 'Angara', loading: 'Caricamento…', loginEyebrow: 'CHAT DIRETTA. SOLO PERSONE SCELTE.', loginTitle: 'Una chat piccola, senza rumore.',
    loginText: 'Accedi con Google per scrivere alle persone che conosci. La tua rubrica non viene memorizzata.', install: 'Installa app', installPhone: 'Installa Angara sul telefono',
    keyEyebrow: 'CHIAVE DEL DISPOSITIVO', keyTitle: 'La cifratura è bloccata.', keyText: 'Angara non può recuperare la chiave dal server: è proprio questa separazione a impedire al server di leggere i messaggi.', logout: 'Esci',
    available: 'Disponibile', newChat: 'Nuova chat', notifications: 'Abilita notifiche', conversations: 'Conversazioni', encryptedMessage: 'Messaggio crittografato', startWriting: 'Inizia a scrivere…', empty: 'Nessuna conversazione. Scegli una persona dalla rubrica.',
    e2ee: 'Cifratura end-to-end', chooseChat: 'Scegli una conversazione', serverCiphertext: 'I messaggi sono conservati sul server. TLS li protegge durante il transito.', back: 'Torna alle conversazioni', verifyKeys: 'Verifica chiavi di sicurezza', message: 'Scrivi un messaggio', send: 'Invia',
    newConversation: 'NUOVA CONVERSAZIONE', findPerson: 'Trova una persona', contactPicker: 'Scegli quali contatti condividere. Nessun dato della rubrica viene conservato.', openContacts: 'Apri la rubrica', orEmail: 'Oppure cerca per email', search: 'Cerca', close: 'Chiudi',
    fingerprints: 'CIFRATURA END-TO-END', securityKeys: 'Chiavi di sicurezza', compareKeys: 'Confronta queste impronte con il contatto usando un canale diverso, idealmente di persona. Se coincidono, il server non ha sostituito le chiavi.', yourDevice: 'Il tuo dispositivo',
    loginFailed: 'Accesso non riuscito. Riprova.', logoutFailed: 'Disconnessione dal server non riuscita; i dati locali sono stati rimossi.', googleUnavailable: 'Google Identity non disponibile. Ricarica la pagina e riprova.', deviceMissing: 'Questo account è già associato a un altro dispositivo. Senza la chiave privata originale i vecchi messaggi non possono essere decifrati.', cryptoFailed: 'Impossibile inizializzare la cifratura su questo dispositivo.', peerNeedsDevice: 'La persona deve aprire Angara sul proprio dispositivo prima di poter ricevere messaggi cifrati.', keyChanged: 'La chiave di sicurezza del contatto è cambiata. Invio bloccato: verifica l’impronta di persona.', messageFailed: 'Messaggio non inviato.', undecipherable: 'Messaggio non decifrabile', noUsers: 'Nessun utente registrato trovato per queste email.', pushFailed: 'Notifiche non abilitate. Su iPhone installa prima l’app nella schermata Home.', keyWarning: 'La chiave del contatto è cambiata: non inviare messaggi finché non l’hai verificata.',
    share: 'Condividi', photo: 'Foto', document: 'Documento', location: 'Posizione', locating: 'Localizzazione…', cancel: 'Annulla', confirmAttachment: 'Inviare questo file?', confirmLocation: 'Condividere questa posizione?', sendLocation: 'Invia posizione', sharedLocation: 'Posizione condivisa', loadMap: 'Carica la mappa', openInOsm: 'Apri in OpenStreetMap', osmPrivacy: 'Al click OSM riceverà IP, orario, origine e area visualizzata.', locationPrivacy: 'Le coordinate precise saranno visibili al destinatario.', photoMetadataWarning: 'La foto originale può contenere metadati del dispositivo e coordinate GPS. Angara non li rimuove.', attachmentTooLarge: 'Il file supera il limite di 8 MB.', attachmentTypeUnsupported: 'Questo formato di file non è supportato.', attachmentFailed: 'Impossibile preparare o inviare il file.', locationUnavailable: 'La posizione non è disponibile su questo dispositivo.', locationFailed: 'Impossibile rilevare o inviare la posizione.', mapFailed: 'Impossibile caricare la mappa. Puoi aprire la posizione in OpenStreetMap.', startCall: 'Avvia chiamata audio', audioCall: 'CHIAMATA AUDIO', incomingCall: 'Chiamata in arrivo', answerCall: 'Rispondi', endCall: 'Termina', calling: 'Chiamata in corso…', callConnected: 'Chiamata connessa', callFailed: 'Impossibile avviare la chiamata.', callPrivacy: 'La chiamata usa WebRTC e può esporre metadati di rete al relay.',
  },
  en: {
    brand: 'Angara', loading: 'Loading…', loginEyebrow: 'DIRECT CHAT. ONLY PEOPLE YOU CHOOSE.', loginTitle: 'A small chat, without the noise.', loginText: 'Sign in with Google to write to people you know. Your contacts are never stored.', install: 'Install app', installPhone: 'Install Angara on your phone',
    keyEyebrow: 'DEVICE KEY', keyTitle: 'Encryption is blocked.', keyText: 'Angara cannot recover the key from the server: that separation is what prevents the server from reading messages.', logout: 'Sign out',
    available: 'Available', newChat: 'New chat', notifications: 'Enable notifications', conversations: 'Conversations', encryptedMessage: 'Encrypted message', startWriting: 'Start writing…', empty: 'No conversations yet. Choose someone from your contacts.',
    e2ee: 'End-to-end encryption', chooseChat: 'Choose a conversation', serverCiphertext: 'Messages are stored on the server. TLS protects them in transit.', back: 'Back to conversations', verifyKeys: 'Verify security keys', message: 'Write a message', send: 'Send',
    newConversation: 'NEW CONVERSATION', findPerson: 'Find someone', contactPicker: 'Choose which contacts to share. No address-book data is retained.', openContacts: 'Open contacts', orEmail: 'Or search by email', search: 'Search', close: 'Close',
    fingerprints: 'END-TO-END ENCRYPTION', securityKeys: 'Security keys', compareKeys: 'Compare these fingerprints with your contact through another channel, ideally in person. If they match, the server has not replaced the keys.', yourDevice: 'Your device',
    loginFailed: 'Sign-in failed. Try again.', logoutFailed: 'Server sign-out failed; local data was removed.', googleUnavailable: 'Google Identity is unavailable. Reload the page and try again.', deviceMissing: 'This account is already associated with another device. Without the original private key, previous messages cannot be decrypted.', cryptoFailed: 'Unable to initialize encryption on this device.', peerNeedsDevice: 'This person needs to open Angara on their device before receiving encrypted messages.', keyChanged: 'This contact’s security key has changed. Sending is blocked: verify the fingerprint first.', messageFailed: 'Message was not sent.', undecipherable: 'Message cannot be decrypted', noUsers: 'No registered users were found for these email addresses.', pushFailed: 'Notifications were not enabled. On iPhone, install the app to the Home Screen first.', keyWarning: 'This contact’s key has changed: do not send messages until you have verified it.',
    share: 'Share', photo: 'Photo', document: 'Document', location: 'Location', locating: 'Locating…', cancel: 'Cancel', confirmAttachment: 'Send this file?', confirmLocation: 'Share this location?', sendLocation: 'Send location', sharedLocation: 'Shared location', loadMap: 'Load map', openInOsm: 'Open in OpenStreetMap', osmPrivacy: 'On click, OSM will receive your IP, time, origin and viewed area.', locationPrivacy: 'The precise coordinates will be visible to the recipient.', photoMetadataWarning: 'The original photo may contain device metadata and GPS coordinates. Angara does not remove them.', attachmentTooLarge: 'The file exceeds the 8 MB limit.', attachmentTypeUnsupported: 'This file format is not supported.', attachmentFailed: 'The file could not be prepared or sent.', locationUnavailable: 'Location is not available on this device.', locationFailed: 'The location could not be detected or sent.', mapFailed: 'The map could not be loaded. You can open the location in OpenStreetMap.', startCall: 'Start audio call', audioCall: 'AUDIO CALL', incomingCall: 'Incoming call', answerCall: 'Answer', endCall: 'End', calling: 'Calling…', callConnected: 'Call connected', callFailed: 'Unable to start the call.', callPrivacy: 'The call uses WebRTC and can expose network metadata to the relay.',
  },
  ru: {
    brand: 'Ангара', loading: 'Загрузка…', loginEyebrow: 'ПРЯМОЙ ЧАТ. ТОЛЬКО ВЫБРАННЫЕ ЛЮДИ.', loginTitle: 'Небольшой чат без лишнего шума.', loginText: 'Войдите через Google, чтобы общаться со знакомыми. Контакты не сохраняются.', install: 'Установить приложение', installPhone: 'Установить Ангару на телефон',
    keyEyebrow: 'КЛЮЧ УСТРОЙСТВА', keyTitle: 'Шифрование заблокировано.', keyText: 'Ангара не может восстановить ключ с сервера: именно это не позволяет серверу читать сообщения.', logout: 'Выйти',
    available: 'Доступен', newChat: 'Новый чат', notifications: 'Включить уведомления', conversations: 'Диалоги', encryptedMessage: 'Зашифрованное сообщение', startWriting: 'Начните писать…', empty: 'Пока нет диалогов. Выберите человека из контактов.',
    e2ee: 'Сквозное шифрование', chooseChat: 'Выберите диалог', serverCiphertext: 'Сообщения хранятся на сервере. TLS защищает их при передаче.', back: 'К диалогам', verifyKeys: 'Проверить ключи безопасности', message: 'Напишите сообщение', send: 'Отправить',
    newConversation: 'НОВЫЙ ДИАЛОГ', findPerson: 'Найти человека', contactPicker: 'Выберите контакты для отправки. Данные адресной книги не сохраняются.', openContacts: 'Открыть контакты', orEmail: 'Или найдите по email', search: 'Найти', close: 'Закрыть',
    fingerprints: 'СКВОЗНОЕ ШИФРОВАНИЕ', securityKeys: 'Ключи безопасности', compareKeys: 'Сверьте эти отпечатки с собеседником через другой канал, лучше лично. Если они совпадают, сервер не подменил ключи.', yourDevice: 'Ваше устройство',
    loginFailed: 'Не удалось войти. Повторите попытку.', logoutFailed: 'Не удалось выйти на сервере; локальные данные удалены.', googleUnavailable: 'Сервис Google Identity недоступен. Обновите страницу и повторите попытку.', deviceMissing: 'Этот аккаунт уже привязан к другому устройству. Без исходного закрытого ключа прежние сообщения нельзя расшифровать.', cryptoFailed: 'Не удалось включить шифрование на этом устройстве.', peerNeedsDevice: 'Собеседнику нужно открыть Ангару на своём устройстве, прежде чем он сможет получать зашифрованные сообщения.', keyChanged: 'Ключ безопасности собеседника изменился. Отправка заблокирована: сначала проверьте отпечаток.', messageFailed: 'Сообщение не отправлено.', undecipherable: 'Не удалось расшифровать сообщение', noUsers: 'Для этих адресов email не найдено зарегистрированных пользователей.', pushFailed: 'Не удалось включить уведомления. На iPhone сначала установите приложение на экран «Домой».', keyWarning: 'Ключ собеседника изменился: не отправляйте сообщения, пока не проверите его.',
    share: 'Поделиться', photo: 'Фото', document: 'Документ', location: 'Местоположение', locating: 'Определение…', cancel: 'Отмена', confirmAttachment: 'Отправить этот файл?', confirmLocation: 'Поделиться этим местоположением?', sendLocation: 'Отправить местоположение', sharedLocation: 'Местоположение', loadMap: 'Загрузить карту', openInOsm: 'Открыть в OpenStreetMap', osmPrivacy: 'После нажатия OSM получит IP, время, источник и область карты.', locationPrivacy: 'Точные координаты будут видны получателю.', photoMetadataWarning: 'Исходное фото может содержать данные устройства и GPS-координаты. Ангара их не удаляет.', attachmentTooLarge: 'Размер файла превышает 8 МБ.', attachmentTypeUnsupported: 'Этот формат файла не поддерживается.', attachmentFailed: 'Не удалось подготовить или отправить файл.', locationUnavailable: 'Геолокация недоступна на этом устройстве.', locationFailed: 'Не удалось определить или отправить местоположение.', mapFailed: 'Не удалось загрузить карту. Местоположение можно открыть в OpenStreetMap.', startCall: 'Начать аудиозвонок', audioCall: 'АУДИОЗВОНОК', incomingCall: 'Входящий звонок', answerCall: 'Ответить', endCall: 'Завершить', calling: 'Вызов…', callConnected: 'Звонок подключён', callFailed: 'Не удалось начать звонок.', callPrivacy: 'Звонок использует WebRTC и может раскрыть сетевые метаданные relay.',
  },
} as const;

export type MessageKey = keyof typeof messages.it;

function browserLocale(): Locale {
  const language = navigator.language.toLowerCase().split('-')[0];
  return supportedLocales.includes(language as Locale) ? language as Locale : 'en';
}

export const locale = ref<Locale>(browserLocale());
export const t = (key: MessageKey) => computed(() => messages[locale.value][key]).value;
